import type { RepoStatus } from "./types";

export const fixtureRepos: RepoStatus[] = [
  {
    id: "api",
    name: "接口服务",
    path: "E:/Git_Repositories/api",
    group: "后端",
    branch: "dev",
    relation: "diverged",
    changeLabel: "⇕ 3",
    hint: "需要人工处理",
    remoteUrl: "https://github.com/example/api",
  },
  {
    id: "web",
    name: "前端",
    path: "E:/Git_Repositories/web",
    group: "Web",
    branch: "main",
    relation: "remote_ahead",
    changeLabel: "↓ 2",
    hint: "可 Pull",
    remoteUrl: "https://github.com/example/web",
  },
  {
    id: "docs",
    name: "文档",
    path: "E:/Git_Repositories/docs",
    group: "文档",
    branch: "main",
    relation: "synced",
    changeLabel: "✓",
    hint: "无需操作",
    remoteUrl: "https://github.com/example/docs",
  },
  {
    id: "lab",
    name: "实验仓库",
    path: "E:/Git_Repositories/lab",
    group: "实验",
    branch: "topic",
    relation: "no_remote",
    changeLabel: "∅",
    hint: "未设置 upstream",
    remoteUrl: null,
  },
];
